import { Product, SaleLog } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  // --- USB DRIVES ---
  {
    id: 'ws-1',
    barcode: '1001',
    name: '4GB USB Flash Drive',
    brand: 'Generic',
    modelName: 'USB 2.0',
    costPrice: 400,
    customerPrice: 0,
    wholesalePrice: 500,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-2',
    barcode: '1002',
    name: '8GB USB Flash Drive',
    brand: 'Generic',
    modelName: 'USB 2.0',
    costPrice: 500,
    customerPrice: 0,
    wholesalePrice: 650,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-3',
    barcode: '1003',
    name: '16GB USB Flash Drive',
    brand: 'Generic',
    modelName: 'USB 2.0',
    costPrice: 650,
    customerPrice: 0,
    wholesalePrice: 800,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-4',
    barcode: '1004',
    name: '32GB USB Flash Drive',
    brand: 'Generic',
    modelName: 'USB 3.0',
    costPrice: 1000,
    customerPrice: 0,
    wholesalePrice: 1200,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-5',
    barcode: '1005',
    name: '64GB USB Flash Drive',
    brand: 'Generic',
    modelName: 'USB 3.0',
    costPrice: 1350,
    customerPrice: 0,
    wholesalePrice: 1600,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-6',
    barcode: '1006',
    name: '128GB USB Flash Drive',
    brand: 'Generic',
    modelName: 'USB 3.0',
    costPrice: 0,
    customerPrice: 0,
    wholesalePrice: 0,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },

  // --- KINGSTON PACKING SD CARDS ---
  {
    id: 'ws-7',
    barcode: '1007',
    name: 'Kingston 4GB Memory Card (Packing)',
    brand: 'Kingston',
    modelName: 'Class 10 SD',
    costPrice: 400,
    customerPrice: 0,
    wholesalePrice: 500,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-8',
    barcode: '1008',
    name: 'Kingston 8GB Memory Card (Packing)',
    brand: 'Kingston',
    modelName: 'Class 10 SD',
    costPrice: 500,
    customerPrice: 0,
    wholesalePrice: 650,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-9',
    barcode: '1009',
    name: 'Kingston 16GB Memory Card (Packing)',
    brand: 'Kingston',
    modelName: 'Class 10 SD',
    costPrice: 650,
    customerPrice: 0,
    wholesalePrice: 800,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-10',
    barcode: '1010',
    name: 'Kingston 32GB Memory Card (Packing)',
    brand: 'Kingston',
    modelName: 'Class 10 SD',
    costPrice: 1000,
    customerPrice: 0,
    wholesalePrice: 1200,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-11',
    barcode: '1011',
    name: 'Kingston 64GB Memory Card (Packing)',
    brand: 'Kingston',
    modelName: 'Class 10 SD',
    costPrice: 1350,
    customerPrice: 0,
    wholesalePrice: 1600,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-12',
    barcode: '1012',
    name: 'Kingston 128GB Memory Card (Packing)',
    brand: 'Kingston',
    modelName: 'Class 10 SD',
    costPrice: 0,
    customerPrice: 0,
    wholesalePrice: 0,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },

  // --- CHARGING SHOES & ADAPTERS ---
  {
    id: 'ws-13',
    barcode: '1013',
    name: 'Oppo / Vivo / Tecno Charger Shoe',
    brand: 'Universal',
    modelName: 'Fast Shoe',
    costPrice: 220,
    customerPrice: 0,
    wholesalePrice: 300,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-14',
    barcode: '1014',
    name: 'Supercharge Charger Shoe',
    brand: 'Universal',
    modelName: 'Supercharge',
    costPrice: 270,
    customerPrice: 0,
    wholesalePrice: 350,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-15',
    barcode: '1015',
    name: '45W Fast Charger',
    brand: 'Universal',
    modelName: '45 Watt',
    costPrice: 550,
    customerPrice: 0,
    wholesalePrice: 700,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-16',
    barcode: '1016',
    name: 'Samsung 25W Adapter',
    brand: 'Samsung',
    modelName: 'EP-TA800',
    costPrice: 320,
    customerPrice: 0,
    wholesalePrice: 400,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-17',
    barcode: '1017',
    name: 'Samsung 25W Charger (with Cable)',
    brand: 'Samsung',
    modelName: '25W + Cable',
    costPrice: 360,
    customerPrice: 0,
    wholesalePrice: 450,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-18',
    barcode: '1018',
    name: 'Samsung 45W Adapter',
    brand: 'Samsung',
    modelName: 'EP-T4510',
    costPrice: 360,
    customerPrice: 0,
    wholesalePrice: 450,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-19',
    barcode: '1019',
    name: 'Samsung 45W Charger (with Cable)',
    brand: 'Samsung',
    modelName: '45W + Cable',
    costPrice: 400,
    customerPrice: 0,
    wholesalePrice: 500,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-20',
    barcode: '1020',
    name: 'Box Charger (Keypad Phone)',
    brand: 'Generic',
    modelName: 'Keypad Box',
    costPrice: 150,
    customerPrice: 0,
    wholesalePrice: 200,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-21',
    barcode: '1021',
    name: 'Box Charger (Type-C)',
    brand: 'Generic',
    modelName: 'Type-C Box',
    costPrice: 350,
    customerPrice: 0,
    wholesalePrice: 450,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-22',
    barcode: '1022',
    name: 'Desktop Charger',
    brand: 'Generic',
    modelName: 'Desktop Dock',
    costPrice: 150,
    customerPrice: 0,
    wholesalePrice: 200,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },

  // --- HANDSFREE ---
  {
    id: 'ws-23',
    barcode: '1023',
    name: 'TURBOX / itel / Larib Handsfree',
    brand: 'Turbox / itel',
    modelName: '3.5mm Pin',
    costPrice: 150,
    customerPrice: 0,
    wholesalePrice: 200,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-24',
    barcode: '1024',
    name: 'M-5 / Blue Spectrum Handsfree',
    brand: 'Blue Spectrum',
    modelName: 'M-5 Stereo',
    costPrice: 160,
    customerPrice: 0,
    wholesalePrice: 220,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },

  // --- DATA CABLE (LOCAL) ---
  {
    id: 'ws-25',
    barcode: '1025',
    name: 'Infinix Data Cable (Local)',
    brand: 'Infinix',
    modelName: 'Local Cable',
    costPrice: 40,
    customerPrice: 0,
    wholesalePrice: 60,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-26',
    barcode: '1026',
    name: 'Kolu Data Cable (Android / Type-C)',
    brand: 'Kolu',
    modelName: 'Android / Type-C',
    costPrice: 70,
    customerPrice: 0,
    wholesalePrice: 100,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-27',
    barcode: '1027',
    name: 'iPhone Data Cable (Local)',
    brand: 'Generic',
    modelName: 'Lightning Local',
    costPrice: 100,
    customerPrice: 0,
    wholesalePrice: 150,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-28',
    barcode: '1028',
    name: 'Type-C to Type-C Cable (Local)',
    brand: 'Generic',
    modelName: 'Type-C to Type-C',
    costPrice: 100,
    customerPrice: 0,
    wholesalePrice: 150,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-29',
    barcode: '1029',
    name: '4 in 1 Multi Data Cable',
    brand: 'Generic',
    modelName: '4-in-1 Cable',
    costPrice: 180,
    customerPrice: 0,
    wholesalePrice: 250,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },

  // --- AIRPODS & TWS ---
  {
    id: 'ws-30',
    barcode: '1030',
    name: 'M-11 Earbud (Single)',
    brand: 'Generic',
    modelName: 'M-11 Single',
    costPrice: 220,
    customerPrice: 0,
    wholesalePrice: 300,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-31',
    barcode: '1031',
    name: 'Air-31 TWS Earbuds',
    brand: 'TWS',
    modelName: 'Air-31 Transparent',
    costPrice: 400,
    customerPrice: 0,
    wholesalePrice: 550,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-32',
    barcode: '1032',
    name: 'AirPods Pro 2 (Small Box)',
    brand: 'TWS',
    modelName: 'Pro 2 Small',
    costPrice: 400,
    customerPrice: 0,
    wholesalePrice: 550,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-33',
    barcode: '1033',
    name: 'AirPods Pro 2 (Large Box)',
    brand: 'TWS',
    modelName: 'Pro 2 Large',
    costPrice: 700,
    customerPrice: 0,
    wholesalePrice: 900,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },

  // --- LOGIN BRAND ACCESSORIES ---
  {
    id: 'ws-34',
    barcode: '1034',
    name: 'Login Android Micro USB Cable',
    brand: 'Login',
    modelName: 'Micro USB',
    costPrice: 180,
    customerPrice: 0,
    wholesalePrice: 250,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-35',
    barcode: '1035',
    name: 'Login Type-C Cable',
    brand: 'Login',
    modelName: 'Type-C Cable',
    costPrice: 220,
    customerPrice: 0,
    wholesalePrice: 300,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-36',
    barcode: '1036',
    name: 'Login iPhone Lightning Cable',
    brand: 'Login',
    modelName: 'Lightning Cable',
    costPrice: 220,
    customerPrice: 0,
    wholesalePrice: 300,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-37',
    barcode: '1037',
    name: 'Login Type-C to Type-C Cable',
    brand: 'Login',
    modelName: 'C-to-C Cable',
    costPrice: 220,
    customerPrice: 0,
    wholesalePrice: 300,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-38',
    barcode: '1038',
    name: 'Login Type-C to iPhone Cable',
    brand: 'Login',
    modelName: 'C-to-Lightning',
    costPrice: 300,
    customerPrice: 0,
    wholesalePrice: 400,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-39',
    barcode: '1039',
    name: 'Login iPhone Fast Charging Cable',
    brand: 'Login',
    modelName: 'Lightning Fast',
    costPrice: 450,
    customerPrice: 0,
    wholesalePrice: 600,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-40',
    barcode: '1040',
    name: 'Login Handsfree (3.5mm Pin)',
    brand: 'Login',
    modelName: '3.5mm Audio',
    costPrice: 320,
    customerPrice: 0,
    wholesalePrice: 450,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-41',
    barcode: '1041',
    name: 'Login Handsfree (Type-C)',
    brand: 'Login',
    modelName: 'Type-C Audio',
    costPrice: 450,
    customerPrice: 0,
    wholesalePrice: 600,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-42',
    barcode: '1042',
    name: 'Login Handsfree (iPhone Lightning)',
    brand: 'Login',
    modelName: 'Lightning Audio',
    costPrice: 600,
    customerPrice: 0,
    wholesalePrice: 800,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-43',
    barcode: '1043',
    name: 'Login Handsfree (iPhone Plug & Play)',
    brand: 'Login',
    modelName: 'Plug & Play Audio',
    costPrice: 950,
    customerPrice: 0,
    wholesalePrice: 1250,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-44',
    barcode: '1044',
    name: 'Login 10,000mAh Power Bank',
    brand: 'Login',
    modelName: '10,000mAh Power',
    costPrice: 2400,
    customerPrice: 0,
    wholesalePrice: 3000,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-45',
    barcode: '1045',
    name: 'Login 20,000mAh Power Bank',
    brand: 'Login',
    modelName: '20,000mAh Power',
    costPrice: 3800,
    customerPrice: 0,
    wholesalePrice: 4800,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },

  // --- RONIN & R-SERIES ACCESSORIES ---
  {
    id: 'ws-46',
    barcode: '1046',
    name: 'R-9 Handsfree (3.5mm Pin)',
    brand: 'Ronin',
    modelName: 'R-9 Pin',
    costPrice: 400,
    customerPrice: 0,
    wholesalePrice: 550,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-47',
    barcode: '1047',
    name: 'R-29 Handsfree (3.5mm Pin)',
    brand: 'Ronin',
    modelName: 'R-29 Pin',
    costPrice: 320,
    customerPrice: 0,
    wholesalePrice: 450,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-48',
    barcode: '1048',
    name: 'R-29 Handsfree (Type-C)',
    brand: 'Ronin',
    modelName: 'R-29 Type-C',
    costPrice: 480,
    customerPrice: 0,
    wholesalePrice: 650,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-49',
    barcode: '1049',
    name: 'R-9 Handsfree (Type-C)',
    brand: 'Ronin',
    modelName: 'R-9 Type-C',
    costPrice: 600,
    customerPrice: 0,
    wholesalePrice: 800,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-50',
    barcode: '1050',
    name: 'Ronin Android Micro USB Cable',
    brand: 'Ronin',
    modelName: 'R-Android',
    costPrice: 220,
    customerPrice: 0,
    wholesalePrice: 300,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-51',
    barcode: '1051',
    name: 'Ronin Type-C Cable',
    brand: 'Ronin',
    modelName: 'R-TypeC',
    costPrice: 250,
    customerPrice: 0,
    wholesalePrice: 350,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-52',
    barcode: '1052',
    name: 'Ronin iPhone Lightning Cable',
    brand: 'Ronin',
    modelName: 'R-iPhone',
    costPrice: 300,
    customerPrice: 0,
    wholesalePrice: 400,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-53',
    barcode: '1053',
    name: 'Ronin Type-C to iPhone Cable',
    brand: 'Ronin',
    modelName: 'R-TypeC to Lightning',
    costPrice: 380,
    customerPrice: 0,
    wholesalePrice: 500,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  },
  {
    id: 'ws-54',
    barcode: '1054',
    name: 'Ronin Type-C to Type-C Cable',
    brand: 'Ronin',
    modelName: 'R-TypeC to TypeC',
    costPrice: 250,
    customerPrice: 0,
    wholesalePrice: 350,
    quantity: 50,
    minQuantity: 5,
    discounts: [5, 10]
  }
];

export const INITIAL_SALES: SaleLog[] = [
  // --- TODAY (2026-08-14) ---
  {
    id: 'sale-today-1',
    productId: 'ws-1',
    productName: '4GB USB Flash Drive',
    barcode: '1001',
    buyerType: 'shopkeeper',
    unitPrice: 500,
    costPrice: 400,
    discountApplied: 0,
    finalPrice: 2500,
    quantity: 5,
    date: '2026-08-14T09:15:00.000Z',
    soldBy: 'Admin',
    customerPhone: '+1-555-0192'
  },
  {
    id: 'sale-today-2',
    productId: 'ws-4',
    productName: '32GB USB Flash Drive',
    barcode: '1004',
    buyerType: 'customer',
    unitPrice: 1200,
    costPrice: 1000,
    discountApplied: 10,
    finalPrice: 1190,
    quantity: 1,
    date: '2026-08-14T11:40:00.000Z',
    soldBy: 'Shoaib',
    customerPhone: '+1-555-0143'
  },
  {
    id: 'sale-today-3',
    productId: 'ws-41',
    productName: 'Ronin R-9 Handsfree',
    barcode: '1041',
    buyerType: 'customer',
    unitPrice: 550,
    costPrice: 450,
    discountApplied: 5,
    finalPrice: 1090,
    quantity: 2,
    date: '2026-08-14T14:20:00.000Z',
    soldBy: 'Zohaib',
    customerPhone: '+1-555-0188'
  },
  {
    id: 'sale-today-4',
    productId: 'ws-48',
    productName: 'Faster 20000mAh Power Bank',
    barcode: '1048',
    buyerType: 'shopkeeper',
    unitPrice: 4500,
    costPrice: 3800,
    discountApplied: 0,
    finalPrice: 9000,
    quantity: 2,
    date: '2026-08-14T16:05:00.000Z',
    soldBy: 'Shoaib',
    customerPhone: '+1-555-0177'
  },

  // --- YESTERDAY (2026-08-13) ---
  {
    id: 'sale-yest-1',
    productId: 'ws-5',
    productName: '64GB USB Flash Drive',
    barcode: '1005',
    buyerType: 'shopkeeper',
    unitPrice: 1600,
    costPrice: 1350,
    discountApplied: 0,
    finalPrice: 4800,
    quantity: 3,
    date: '2026-08-13T10:30:00.000Z',
    soldBy: 'Shoaib',
    customerPhone: '+1-555-0122'
  },
  {
    id: 'sale-yest-2',
    productId: 'ws-34',
    productName: 'Samsung 25W Fast Adapter',
    barcode: '1034',
    buyerType: 'customer',
    unitPrice: 950,
    costPrice: 700,
    discountApplied: 10,
    finalPrice: 940,
    quantity: 1,
    date: '2026-08-13T13:45:00.000Z',
    soldBy: 'Zohaib',
    customerPhone: '+1-555-0133'
  },
  {
    id: 'sale-yest-3',
    productId: 'ws-53',
    productName: 'Ronin Type-C to iPhone Cable',
    barcode: '1053',
    buyerType: 'customer',
    unitPrice: 500,
    costPrice: 380,
    discountApplied: 5,
    finalPrice: 990,
    quantity: 2,
    date: '2026-08-13T17:10:00.000Z',
    soldBy: 'Admin',
    customerPhone: '+1-555-0155'
  },

  // --- AUGUST 2026 (Earlier this month) ---
  {
    id: 'sale-aug-1',
    productId: 'ws-47',
    productName: 'Faster 10000mAh Power Bank',
    barcode: '1047',
    buyerType: 'shopkeeper',
    unitPrice: 3000,
    costPrice: 2400,
    discountApplied: 0,
    finalPrice: 12000,
    quantity: 4,
    date: '2026-08-10T11:00:00.000Z',
    soldBy: 'Admin',
    customerPhone: '+1-555-0199'
  },
  {
    id: 'sale-aug-2',
    productId: 'ws-22',
    productName: 'Type-C Braided Fast Cable',
    barcode: '1022',
    buyerType: 'customer',
    unitPrice: 200,
    costPrice: 150,
    discountApplied: 0,
    finalPrice: 600,
    quantity: 3,
    date: '2026-08-08T15:20:00.000Z',
    soldBy: 'Shoaib'
  },
  {
    id: 'sale-aug-3',
    productId: 'ws-14',
    productName: '32GB Micro SD Card',
    barcode: '1014',
    buyerType: 'shopkeeper',
    unitPrice: 1200,
    costPrice: 1000,
    discountApplied: 0,
    finalPrice: 6000,
    quantity: 5,
    date: '2026-08-05T12:15:00.000Z',
    soldBy: 'Admin'
  },
  {
    id: 'sale-aug-4',
    productId: 'ws-40',
    productName: 'Ronin R-210 Wireless Earbuds',
    barcode: '1040',
    buyerType: 'customer',
    unitPrice: 750,
    costPrice: 600,
    discountApplied: 10,
    finalPrice: 740,
    quantity: 1,
    date: '2026-08-02T16:30:00.000Z',
    soldBy: 'Zohaib'
  },

  // --- JULY 2026 ---
  {
    id: 'sale-jul-1',
    productId: 'ws-48',
    productName: 'Faster 20000mAh Power Bank',
    barcode: '1048',
    buyerType: 'shopkeeper',
    unitPrice: 4500,
    costPrice: 3800,
    discountApplied: 0,
    finalPrice: 18000,
    quantity: 4,
    date: '2026-07-25T14:00:00.000Z',
    soldBy: 'Admin'
  },
  {
    id: 'sale-jul-2',
    productId: 'ws-4',
    productName: '32GB USB Flash Drive',
    barcode: '1004',
    buyerType: 'shopkeeper',
    unitPrice: 1200,
    costPrice: 1000,
    discountApplied: 0,
    finalPrice: 12000,
    quantity: 10,
    date: '2026-07-18T10:45:00.000Z',
    soldBy: 'Shoaib'
  },
  {
    id: 'sale-jul-3',
    productId: 'ws-34',
    productName: 'Samsung 25W Fast Adapter',
    barcode: '1034',
    buyerType: 'customer',
    unitPrice: 950,
    costPrice: 700,
    discountApplied: 10,
    finalPrice: 1880,
    quantity: 2,
    date: '2026-07-10T16:20:00.000Z',
    soldBy: 'Zohaib'
  },

  // --- JUNE 2026 ---
  {
    id: 'sale-jun-1',
    productId: 'ws-47',
    productName: 'Faster 10000mAh Power Bank',
    barcode: '1047',
    buyerType: 'shopkeeper',
    unitPrice: 3000,
    costPrice: 2400,
    discountApplied: 0,
    finalPrice: 15000,
    quantity: 5,
    date: '2026-06-22T11:15:00.000Z',
    soldBy: 'Admin'
  },
  {
    id: 'sale-jun-2',
    productId: 'ws-5',
    productName: '64GB USB Flash Drive',
    barcode: '1005',
    buyerType: 'shopkeeper',
    unitPrice: 1600,
    costPrice: 1350,
    discountApplied: 0,
    finalPrice: 9600,
    quantity: 6,
    date: '2026-06-12T15:00:00.000Z',
    soldBy: 'Shoaib'
  },

  // --- MAY 2026 ---
  {
    id: 'sale-may-1',
    productId: 'ws-48',
    productName: 'Faster 20000mAh Power Bank',
    barcode: '1048',
    buyerType: 'shopkeeper',
    unitPrice: 4500,
    costPrice: 3800,
    discountApplied: 0,
    finalPrice: 22500,
    quantity: 5,
    date: '2026-05-19T13:30:00.000Z',
    soldBy: 'Admin'
  },
  {
    id: 'sale-may-2',
    productId: 'ws-3',
    productName: '16GB USB Flash Drive',
    barcode: '1003',
    buyerType: 'shopkeeper',
    unitPrice: 800,
    costPrice: 650,
    discountApplied: 0,
    finalPrice: 8000,
    quantity: 10,
    date: '2026-05-08T09:40:00.000Z',
    soldBy: 'Shoaib'
  },

  // --- APRIL 2026 ---
  {
    id: 'sale-apr-1',
    productId: 'ws-47',
    productName: 'Faster 10000mAh Power Bank',
    barcode: '1047',
    buyerType: 'shopkeeper',
    unitPrice: 3000,
    costPrice: 2400,
    discountApplied: 0,
    finalPrice: 18000,
    quantity: 6,
    date: '2026-04-16T14:10:00.000Z',
    soldBy: 'Admin'
  },

  // --- MARCH 2026 ---
  {
    id: 'sale-mar-1',
    productId: 'ws-4',
    productName: '32GB USB Flash Drive',
    barcode: '1004',
    buyerType: 'shopkeeper',
    unitPrice: 1200,
    costPrice: 1000,
    discountApplied: 0,
    finalPrice: 14400,
    quantity: 12,
    date: '2026-03-21T12:00:00.000Z',
    soldBy: 'Shoaib'
  },

  // --- FEBRUARY 2026 ---
  {
    id: 'sale-feb-1',
    productId: 'ws-5',
    productName: '64GB USB Flash Drive',
    barcode: '1005',
    buyerType: 'shopkeeper',
    unitPrice: 1600,
    costPrice: 1350,
    discountApplied: 0,
    finalPrice: 11200,
    quantity: 7,
    date: '2026-02-14T15:45:00.000Z',
    soldBy: 'Admin'
  },

  // --- JANUARY 2026 ---
  {
    id: 'sale-jan-1',
    productId: 'ws-48',
    productName: 'Faster 20000mAh Power Bank',
    barcode: '1048',
    buyerType: 'shopkeeper',
    unitPrice: 4500,
    costPrice: 3800,
    discountApplied: 0,
    finalPrice: 27000,
    quantity: 6,
    date: '2026-01-10T10:30:00.000Z',
    soldBy: 'Admin'
  },

  // --- YEAR 2025 ARCHIVE SAMPLES ---
  {
    id: 'sale-2025-1',
    productId: 'ws-4',
    productName: '32GB USB Flash Drive',
    barcode: '1004',
    buyerType: 'shopkeeper',
    unitPrice: 1200,
    costPrice: 1000,
    discountApplied: 0,
    finalPrice: 36000,
    quantity: 30,
    date: '2025-11-20T11:00:00.000Z',
    soldBy: 'Admin'
  },
  {
    id: 'sale-2025-2',
    productId: 'ws-48',
    productName: 'Faster 20000mAh Power Bank',
    barcode: '1048',
    buyerType: 'shopkeeper',
    unitPrice: 4500,
    costPrice: 3800,
    discountApplied: 0,
    finalPrice: 45000,
    quantity: 10,
    date: '2025-08-15T16:00:00.000Z',
    soldBy: 'Shoaib'
  }
];

